# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1677e0f3d101ddd3ff6e3f752d2711392dfe282bc6cdea2c6eac5ba140a1d61c92c0a37e564f589c8cc13939f339958db064bfcc52fc40a95016a13e42f0d679

test:
  secret_key_base: 6e5cc7e6b3528a035890d4a8314cc357738d0575b582aca0a21fb549c1f4e9d64900df8b5ab5858297491a5101a8d5b9dd5e0c5af6f32c527c05f01c3fede03d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
